# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b5be0114325ff9b67965a73a3e09e5bc08151340db28a14a670132c6833b6f5c049797f626eb2d8934b6974ae45f0cf8da2dc47d128bb5f70dc79f4cb3459d

test:
  secret_key_base: a878896978f66971f69e0b8916a641af0d3091d5a24d37bc374cdf6ddaf478b4705ba8ebb5e2e4f39930c5eabed9a8793b1a906e953e1f464d1c5e3d32c3d0d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
